### ISSUE TITLE
Release pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/tyrus#636]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by Tomas-Kraus** [comment]
Release job is available on https://ci.eclipse.org/tyrus/job/tyrus-master-release/
Unfortunately Tyrus CLI Client build is broken and job fails with following error:
```
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:2.4.0:bundle (default-bundle) on project tyrus-client-cli: Internal error in maven-bundle-plugin: Problem writing resource META-INF/maven/org.glassfish.tyrus.ext/tyrus-client-cli/pom.xml: /jobs/genie.tyrus/tyrus-master-release/workspace/ext/client-cli/target/pom.xml (No such file or directory)
```
There is a huge stack trace with following  excepton messages:
```
java.lang.Exception: Problem writing resource META-INF/maven/org.glassfish.tyrus.ext/tyrus-client-cli/pom.xml
java.io.FileNotFoundException: /jobs/genie.tyrus/tyrus-master-release/workspace/ext/client-cli/target/pom.xml 
```

**Comment by Tomas-Kraus** [comment]
Created issue 644 to fix pom. Closing this issue.
