### ISSUE TITLE
JDK client can hang when try to reconnect in bad network connection conditions

### ISSUE THREAD

**Issue by greenmancm** [eclipse-ee4j/tyrus#646]
When using secure connection (wss) while in the conditions of a bad network connection, the client connection thread can hang in dead lock on the JdkClientContainer's connectSynchronously() method, because it never receives neither completed() nor failed() callback. 

There is a good way to reproduce the issue:
1. Use client to establish secure websocket connection.
2. Run `sudo tcpkill -i ${networkInterfaceId} -9 port ${httpsPort}` for about 2 minutes. The client will make several reconnect attempts, then hang. I used the Java Mission Control tool to observe tyrus's threads. For every connection attempt, a new thread was spawned. Then the tyrus connection thread gets stuck, and new threads are not spawning.
3. Stop tcpkill to restore network. The thread is still stuck.

There is a workaround for this bug. However, I don't have full understanding of how it may impact other use cases.
By my observations, when the bug is reproduced, in the ClientFilter the processConnectionClosed() method is called, and wsConnection == null.
If I explicitly call `connectCompletionHandler.failed(null);` here, the dead lock doesn't occur.

This issue probably duplicates #594.

**Comment by lprimak** [comment]
@jansupol this issue can be closed
