### ISSUE TITLE
Project GitHub Pages is not enabled for your project

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/tyrus#681]
I see that you have the `gh-pages` branch created, with content, and kept somewhat up to date.

But the website isn't enabled.

Tested the following URLs:

* https://eclipse-ee4j.github.io/tyrus/
* https://eclipse-ee4j.github.io/tyrus/LICENSE.md
* https://eclipse-ee4j.github.io/tyrus/docs/api/index.html

You'll want to submit a bugzilla request to webmaster to get that enabled.
Example bugzilla (that Jakarta WebSocket API) requested - https://bugs.eclipse.org/549695

I'm asking for this, as the Jakarta WebSocket API will need to put the TCK results on your project (the implementation) web page.
Stay tuned for PR against `gh-pages` for this.
Example TCK results page: https://eclipse-ee4j.github.io/websocket-api/TCK-Results.html (sorry, it's slightly out of date)

**Comment by bshannon** [comment]
I enabled GitHub Pages.
