### ISSUE TITLE
#getInstalledExtensions() never called in container

### ISSUE THREAD

**Issue by dansiviter** [eclipse-ee4j/tyrus#694]
It seems there is no way of defining default Extensions to be used in Tyrus (e.g. per-message deflate). It seems the `TyrusServerContainer#getInstalledExtensions()` is never called and therefore does not get populated into `DefaultServerEndpointConfig`.

The only way is to manually define the application via `DefaultServerEndpointConfig.Builder` which precludes annotated endpoints from using it. There is a separate question about weather `@ServerEndpoint` annotation should also define a `extensions` field, but I've raised that in the Spec project (eclipse-ee4j/websocket-api#327).

**Comment by dansiviter** [comment]
FYI it appears [Undertow uses](/undertow-io/undertow/blob/master/websockets-jsr/src/main/java/io/undertow/websockets/jsr/ServerWebSocketContainer.java) `#installedExtensions` as a basis of all endpoints if defined but Tyrus doesn't. The spec isn't all that clear, but I would have imagined that it would use the `#installedExtensions` as a basis and append any that are also defined in `ServerEndpointConfig#extensions`

**Comment by jansupol** [comment]
Fixed by #695
