### ISSUE TITLE
GlassFish needs an M2 release

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/tyrus#704]
GlassFish needs an M2 release incorporating https://github.com/eclipse-ee4j/tyrus/pull/701 for the June milestone release

**Comment by jansupol** [comment]
Sorry, I thought we have done this, will check what happened. Maybe an issue with updating to 1.0.6 parent pom

**Comment by jansupol** [comment]
Done, thanks @senivam.

**Comment by smillidge** [comment]
thanks
