### ISSUE TITLE
How to start Tyrus on an *existing* Grizzly instance?

### ISSUE THREAD

**Issue by zenbones** [eclipse-ee4j/tyrus#735]
Do you have instructions for adding Tyrus to an existing Grizzly instance? This is as opposed to starting up a new network listener etc.

**Comment by jansupol** [comment]
Apparently, there is no experience with this.

Tyrus Framework has the capability of being deployed to a running server in a form of a web application (WAR), where this is deployed to a Servlet Container. Grizzly NIO server does not provide a Servlet container implementation, and the integration with Grizzly is done through a Grizzly listener added to a Grizzly Server. See [GrizzlyServerContainer](https://github.com/eclipse-ee4j/tyrus/blob/master/containers/grizzly-server/src/main/java/org/glassfish/tyrus/container/grizzly/server/GrizzlyServerContainer.java).

This listener is added before the Grizzly Server is started and it is more a [question for the Grizzly framework](https://github.com/eclipse-ee4j/grizzly/issues) whether they allow adding a listener once the Grizzly is already started.

**Comment by zenbones** [comment]
There *was* no experience with this. I have the code to create the Grizzly server with Tyrus, in Spring, all in code, no .war file. Available open source in the SmallMind project in maven central and GitHub if anyone needs it.
