### ISSUE TITLE
tyrus-client-java8-2.0.2 client depends on tyrus-client-2.0.2, which is built for Java 11

### ISSUE THREAD

**Issue by lwahonen** [eclipse-ee4j/tyrus#782]
Is this by design? I could not find documentation for the various components, so I assumed tyrus-client-java8 to be JVM 8 compatible.

**Comment by lwahonen** [comment]
The documentation I could find ( https://eclipse-ee4j.github.io/tyrus-project.github.io/documentation/latest/index/modules-and-dependencies.html ) states "All Tyrus components are built using Java SE 7 compiler. It means, you will also need at least Java SE 7 to be able to compile and run your application."

**Comment by jansupol** [comment]
We need to update the documentation, it seems. Basically, the version which is supported is derived from the Eclipse Jakarta EE project. Jakarta EE 10 supports JDK 11, minimum. Tyrus 2.0.2 is a bridge release between Tyrus 2.1 (Jakarta EE 10) and 2.0 (Jakarta EE 9) and it supports JDK 11, minimum. Please use Tyrus 2.0.1 for JDK 8 support.

**Comment by lwahonen** [comment]
tyrus-client-java8 2.0.1 results in `java.lang.NoClassDefFoundError: javax/websocket/ClientEndpointConfig$Configurator` when doing a simple         `StandardWebSocketClient webSocketClient = new StandardWebSocketClient();`.

I bet I'm missing some other libraries, which aren't marked as dependencies on the jar.

However, with tyrus-container-jdk-client 1.18 things work nicely. Using that for now, hoping that the 1.x branch keeps getting security patches as needed.

Thanks!

**Comment by jansupol** [comment]
With Tyrus 2.x, WebSocket API 2.x is required.
