### ISSUE TITLE
Want changelog / release notes

### ISSUE THREAD

**Issue by basil** [eclipse-ee4j/tyrus#802]
As a consumer of this library, I would find it helpful if a changelog or release notes were published so that I can assess the risk of upgrading. Some previous upgrades contained a Jakarta migration and the requirement of Java 11, neither of which were documented. This made upgrading more painful than it needed to be.

**Comment by jansupol** [comment]
@basil Sorry for that. Similarly to glassfish 6.1.0+ which requires JDK 11, Tyrus 2.0.x also started to require JDK 11. If that is an issue for the customers, we may consider supporting JDK 8 again. Please let us know.

Tyrus does not have the release notes per se. It has a [list of releases](https://github.com/eclipse-ee4j/tyrus/releases) with a change log. There also is a list of releases on the [Eclipse Project site](https://projects.eclipse.org/projects/ee4j.tyrus) that contains a short summary of new and noteworthy features.

**Comment by basil** [comment]
Thanks for the response! I was not suggesting a move back to Java 8: we also [require Java 11 or newer](https://www.jenkins.io/blog/2022/06/28/require-java-11/) and believe this is the right direction for the community. I had seen https://github.com/eclipse-ee4j/tyrus/releases but not https://projects.eclipse.org/projects/ee4j.tyrus. The latter will be helpful in the future. For examples of some of the confusion we faced in the past, see https://github.com/jenkinsci/remoting/pull/423 and https://github.com/jenkinsci/remoting/pull/477.

**Comment by jansupol** [comment]
@basil It should have been updated by now.
