### ISSUE TITLE
Jakarta WebSockets implementation version?

### ISSUE THREAD

**Issue by quaddan** [eclipse-ee4j/tyrus#843]
It seems to me, although I may be wrong, that  Tyrus is based on `Jakarta WebSockets 1.1.1`.

In the [tyrus/pom.xml](https://github.com/eclipse-ee4j/tyrus/blob/master/pom.xml) I can read the following:

```
<websocket-api.version>1.1.1</websocket-api.version>

<dependency>
    <groupId>jakarta.websocket</groupId>
    <artifactId>jakarta.websocket-api</artifactId>
    <version>${websocket-api.version}</version>
</dependency>
<dependency>
    <groupId>jakarta.websocket</groupId>
    <artifactId>jakarta.websocket-client-api</artifactId>
    <version>${websocket-api.version}</version>
</dependency>
```

**Comment by quaddan** [comment]
Could you be as quick to answer my question as you were to close my request if there was still someone here (immediate response)?
This is a technical question. 
Thank you for your understanding.

**Comment by jansupol** [comment]
Tyrus

- [master](https://github.com/eclipse-ee4j/tyrus/tree/master) branch (Jakarta EE 8) is using WebSocket 1.1.1 API
- [2.0.x](https://github.com/eclipse-ee4j/tyrus/blob/2.0.x/pom.xml) branch (Jakarta EE 9) is using WebSocket 2.0.0 API
- [2.x](https://github.com/eclipse-ee4j/tyrus/blob/2.x/pom.xml) branch (Jakarta EE 10) is using WebSocket 2.1.0 API.

It is possible to check in [maven central](https://mvnrepository.com/artifact/org.glassfish.tyrus/tyrus-spi) each version of Tyrus and the API dependency.

**Comment by jansupol** [comment]
You are looking into the master branch, which is Jakarta EE 8 (WebSocket 1.1) implementation. If you want WebSocket 2.1 Tyrus implementation, please check the [2.x](https://github.com/eclipse-ee4j/tyrus/blob/2.x/pom.xml) branch.

**Comment by quaddan** [comment]
Ah ok.
Thank you very much.
