### ISSUE TITLE
About reconnect synchronization

### ISSUE THREAD

**Issue by barisyild** [eclipse-ee4j/tyrus#859]
Is it possible to synchronize the packets of the reconnected client on server-side?

If this is possible, how can we do this?

**Comment by jansupol** [comment]
What do you mean by synchronizing packets? The server does not keep messages that once have been sent while the client was not connected.

**Comment by barisyild** [comment]
I want to synchronize the state if the user reconnects until the reconnect timeout.

**Comment by barisyild** [comment]
> Tyrus supports a [ReconnectHandler](https://eclipse-ee4j.github.io/tyrus-project.github.io/apidocs/latest/org/glassfish/tyrus/client/ClientManager.ReconnectHandler.html) that manages the reconnection if that's what you look for. Look at the [doc](https://eclipse-ee4j.github.io/tyrus-project.github.io/documentation/latest/index/tyrus-proprietary-config.html#d0e1471) for details.

So, are the packets that need to be transmitted to the user transmitted when the user reconnects?

**Comment by jansupol** [comment]
The reconnection can take seconds or might not happen at all. There are no resources to store messages and wait for the reconnection whether it happens or not.
