### ISSUE TITLE
Add module-info

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/tyrus#867]

**Comment by jansupol** [comment]
Hi Manfred, Tyrus 2.0.x (Jakarta EE 9) and Tyrus 2.1.x (Jakarta EE 10) do have module-info

**Comment by mnriem** [comment]
@jansupol I missed that. Note that the module-info then needs to be updated for Grizzly 4.0.1 as Grizzly now has different module names.

**Comment by jansupol** [comment]
@mnriem Good to know, thank you!

**Comment by jansupol** [comment]
@mnriem Grizzly has the module-info dodgy.
in `grizzly-http-server`, the pom says:
```
        <dependency>
            <groupId>org.glassfish.gmbal</groupId>
            <artifactId>gmbal</artifactId>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>
```
but the module-info has a hard dependency on half of the glassfish:
```
    requires gmbal;
    requires org.glassfish.external.management.api;
    requires pfl.basic;
    requires pfl.tf;
    requires org.objectweb.asm;
    requires pfl.dynamic;
    requires org.objectweb.asm.util;
    requires org.objectweb.asm.tree;
    requires org.objectweb.asm.tree.analysis;
    requires pfl.basic.tools;
    requires pfl.tf.tools;
    requires org.objectweb.asm.commons;
```
The requirements should be static.

**Comment by mnriem** [comment]
@arjantijms What do you think?

**Comment by jansupol** [comment]
@mnriem @arjantijms Yes, the changes in Grizzly master are exactly what Tyrus would need. Thanks!

**Comment by mnriem** [comment]
@jansupol The 4.0.2 Grizzly release is out the door!

**Comment by jansupol** [comment]
@mnriem Thank you!!! Do you know what Glassfish will consume this Grizzly with JPMS, will it be Glassfish 8, or 7 as well?

**Comment by jansupol** [comment]
For EE11: #876

**Comment by mnriem** [comment]
It was integrated into Glassfish 7.0.12, see https://github.com/eclipse-ee4j/glassfish/pull/24713

**Comment by jansupol** [comment]
Yes, it does. We will update it in EE 10 Tyrus, too. Thanks @mnriem !
